services:
  postgres:
    container_name: feedbackbite-postgres
    image: postgres:17
    command: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: feedbackbite
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    stop_grace_period: 1s

volumes:
  postgres_data:
    name: feedbackbite-app_postgres_data
